# Generated by Django 2.2.1 on 2019-09-14 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 17, 40, 8, 936432), verbose_name='date published'),
        ),
    ]
