# Generated by Django 2.2.1 on 2019-09-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190914_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
